apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: database:5432
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: smart_monitor
      sslmode: "disable"
      timescaledb: true
      timeInterval: "10s"
      postgresVersion: 1500
      maxOpenConns: 50
      maxIdleConns: 10
      connMaxLifetime: 14400
